### ISSUE TITLE
Unable to build under Cygwin

### ISSUE THREAD

**Issue by jaybird110127** [micahcowan/bobbin#3]
I barely know what I'm doing, but when I try to build this under Cygwin, I get as far as running make, then I get:

Making all in src
interfaces/tty.c: In function ‘if_tty_start’:
interfaces/tty.c:265:13: error: lvalue required as left operand of assignment
  265 |     ESCDELAY=17; // Wait 1/60th of a second to see if an escape char
      |             ^
make[2]: *** [Makefile:525: interfaces/tty.o] Error 1
make[1]: *** [Makefile:343: all] Error 2
make: *** [Makefile:422: all-recursive] Error 1

What's going on? Thanks.

**Comment by jaybird110127** [comment]
I commented out that line and was able to build it, but the Ncurses interface still won't work for me, which really doesn't matter as I'm blind, and that interface seems to be doing something that messes up my screen reader. For anyone else though, trying to run Bobbin.exe produces:
Error opening terminal: xterm-256color.

**Comment by micahcowan** [comment]
I wonder how old a version of ncurses is being used on Cygwin... ESCDELAY is an ncurses-specific variable (other implementations of the curses API do not have it, or in one case, has it but responds differently to it). It's mostly harmless to leave it out, except that typing the Escape key might not be acknowledged until another key is pressed, or perhaps after about a second has passed. The latest versions of ncurses definitely have it, and as far as I know, have had it for a very long time.

The "Error opening terminal" message suggests that you have the TERM environment variable set to xterm-256color (it may have been set automatically by a terminal emulator program you are using, or might be set in your .bashrc or what have you), but that ncurses can't find a definition for a terminal by that name, and so doesn't know what kinds of control-sequences to send. Ncurses has included definitions for that terminal for quite some time, so this represents an unusual situation. It's probably fixable if you can find the correct terminal definitions for it (perhaps from the source distribution for a newer ncurses release), and run the "tic" command on it (for TermInfo Compile - which might or might not have come with your ncurses install). It might be easier to set TERM to a different value that your ncurses distribution does have a definition for. Possibly "xterm", or "vt100".

**Comment by micahcowan** [comment]
I confess I had not previously considered the fact that bobbin may be ideally suited for use with a screen reader, or other tools for people with visual impairments, particularly once I've implemented sound support. What Apple II emulators have you been using prior to now, that have been reasonably usable for you?

**Comment by jaybird110127** [comment]
In 2000 I found and started using an even then positively ancient emulator called A2 by Rich Skrenta. It was written to run under Linux, but the author got it to compile with DJGPP under DOS, which was what I was using at the time. That lasted me until I graduated to machines that couldn't run DOS any more, at which point I was stuck. Most if not all other Apple emulators don't expose the text of the Apple screen in a way that screen readers can access it. On real Apples, I use an Echo II speech synthesizer, which was developed by Street Electronics Corp. No emulator supported the Echo, until MESS in 2013 or so. So that's what I've been using, MESS, then MAME. The problem is that the MAME UI is not accessible to screen readers, so I can't easily do things like change disks, etc. So as you can imagine, I was excited to stumble across Bobbin, a text mode Apple emulator.
