### ISSUE TITLE
Save a transcript to a file

### ISSUE THREAD

**Issue by jaybird110127** [micahcowan/bobbin#5]
I know this is easy to do on Linux, but not so much on Windows. Could we have a command lline option and possibly a debugger command to log all input and output to a text file?

**Comment by micahcowan** [comment]
I think it's probably best to leave this sort of thing to the dedicated tools that exist to do this. If you're in a Cygwin shell, you should just be able to run `./bobbin -m plus --simple 2>&1 | tee transcript.txt`; the main issue with this is that if you type HELLO, then type backspace over that and type a new world "HIYA", the transcript will contain something like HELLO^H^H^H^HIYA. But if you `cat` the file it will look right, and there are probably tools out there that can massage the backspaces appropriately.

A better tool for the job would be something like script (from bsdutils), or ttyrec... but I'm uncertain whether those build on Cygwin (bsdutils is probably unlikely to I guess).
